name: Hello World
author: Sergio Bermudez
description: Example
inputs:
  who-to-greet:
     description: 'Who to greet'
     required: true
     default: Sergio
  outputs:
    time:
      description: 'The greeting time'
  runs:
    using: 'node12'
    main: 'dist/index.js'