# Publish ALL RSI packages in GitHub Packages
name: Publish Rsi packages

on: push

env:
  DOTNET_VERSION: '6.x.x'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: 'https://nuget.pkg.github.com/revenue-solutions-inc/index.json'
  PATH_NUGET: 'SayHi.csproj'


jobs:
  Package-Rsi-Core:
    name: 'Publish SayHi'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2