# Publish ALL RSI packages in GitHub Packages
name: Publish Rsi packages

on: push

env:
  DOTNET_VERSION: '6.x.x'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: 'https://nuget.pkg.github.com/sbermudez-rsi/index.json'
  PATH_NUGET: 'SayHi.csproj'


jobs:
  Package-Rsi-Core:
    name: 'Publish SayHi'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install DotNet X SDK
      - name: 'Install dotnet'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '${{env.DOTNET_VERSION}}'
          include-prerelease: true

      # Dotne nuget add source
      - name: 'Nuget Add Source'
        run: dotnet nuget add source --username @sbermudez-rsi --password ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text --name 'github' '${{env.NUGET_SOURCE_URL}}'

      # Restore Packages
      - name: 'Restore Packages SayHi'
        run: dotnet restore ${{env.PATH_NUGET}}
      # Build Project
      - name: 'Build Project SayHi'
        run: dotnet build ${{env.PATH_NUGET}} --no-restore --configuration Release
      # Pack the project
      - name: 'Pack Project SayHi'
        run: dotnet pack ${{env.PATH_NUGET}} --no-restore --no-build --configuration Release --include-symbols --output ${{env.PACKAGE_OUTPUT_DIRECTORY}}
      # Push the package
      - name: 'Push Package SayHi'
        run: |
          dotnet nuget push '${{env.PACKAGE_OUTPUT_DIRECTORY}}/*.nupkg' -s 'github' --api-key ${{secrets.GITHUB_TOKEN}} --skip-duplicate
          rm output/*.*