name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch

env:
  DOTNET_VERSION: '6.x.x'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: 'https://nuget.pkg.github.com/sbermudez-rsi/index.json'
  PATH_NUGET: 'SayHi.csproj'
  NUGET_KEY: ${{secrets.GITHUB_TOKEN}}

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install DotNet X SDK
      - name: 'Install dotnet'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '${{env.DOTNET_VERSION}}'
          include-prerelease: true

      # Dotne nuget add source
      - name: 'Nuget Add Source'
        run: dotnet nuget add source --username revenue-solutions-inc --password ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text --name 'github' '${{env.NUGET_SOURCE_URL}}'          

      # Install @octokit/core
      - name: 'Install @octokit/core'
        run: npm install @octokit/core

      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: ./.github/actions/checkVersion        
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: SayHi.csproj
          NUGET_KEY: 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     #${{secrets.GITHUB_TOKEN}}
          
