name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Publish
#      - name: publish on version change
#        id: publish_nuget
#        uses: ./.github/actions/checkVersion        
#        with:
          # Filepath of the project to be packaged, relative to root of repository
#          PROJECT_FILE_PATH: SayHi.csproj
          
