name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch

env:
  DOTNET_VERSION: '6.x.x'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: 'https://nuget.pkg.github.com/sbermudez-rsi'
  PATH_NUGET: 'SayHi.csproj'
  NUGET_KEY: ${{secrets.GITHUB_TOKEN}}

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install DotNet X SDK
      - name: 'Install dotnet'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '${{env.DOTNET_VERSION}}'
          include-prerelease: true

      # Install @octokit/core
      - name: 'Install @octokit/core'
        run: npm install @octokit/core

      # Get package
      - name: 'Get Package'
        run: |
          curl -H "Accept: application/vnd.github.v3+json" https://nuget.pkg.github.com/sbermudez-rsi/myPackages/index.json


      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: ./.github/actions/checkVersion        
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: SayHi.csproj
          NUGET_KEY: ${{secrets.GITHUB_TOKEN}}
          
